name: Testing workflow
on:
  pull_request:
    branches:
      - develop
      - staging
      
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js 21.x
        uses: actions/setup-node@v1
        with:
          node-version: 21.x

      # Install dependencies
      - name: Install Dependencies
        run: |
          npm install
          cd client && npm install
          cd ../server && npm install
          cd ..

      # Build project (adjust if only client needs building)
      - name: Run Build
        run: npm run build

      # Start the server in the background and wait for it to be ready
      - name: Start Server and Wait
        run: |
          cd server
          npm start &
          sleep 3
          curl http://localhost:3001 || echo "Server not yet responding"
          npx wait-on http://localhost:3001
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      # Run Cypress component tests
      - name: Run Cypress Tests
        run: npm run test-component
